language: java

jdk:
  - oraclejdk7

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx2048m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
 - "umask 022"
 - "mkdir inputs"

notifications:
  slack: ukwebarchive:oqbYOo0bd09bnSXn4hGR1aUk
