language: java

dist: trusty

sudo: required

jdk:
  - openjdk8
  - openjdk11

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx2048m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
 - "umask 022"
 - "mkdir inputs"

cache:
  directories:
  - $HOME/.m2

